import el from './el';

export function div() { return el("div", ...arguments); }
export function span() { return el("span", ...arguments); }
export function a() { return el("a", ...arguments); }
export function p() { return el("p", ...arguments); }
export function h1() { return el("h1", ...arguments); }
export function h2() { return el("h2", ...arguments); }
export function h3() { return el("h3", ...arguments); }
export function h4() { return el("h4", ...arguments); }
export function h5() { return el("h5", ...arguments); }
export function h6() { return el("h6", ...arguments); }
export function ul() { return el("ul", ...arguments); }
export function ol() { return el("ol", ...arguments); }
export function li() { return el("li", ...arguments); }
export function img() { return el("img", ...arguments); }
export function table() { return el("table", ...arguments); }
export function tr() { return el("tr", ...arguments); }
export function td() { return el("td", ...arguments); }
export function th() { return el("th", ...arguments); }
export function form() { return el("form", ...arguments); }
export function input() { return el("input", ...arguments); }
export function button() { return el("button", ...arguments); }
export function label() { return el("label", ...arguments); }
export function textarea() { return el("textarea", ...arguments); }
export function select() { return el("select", ...arguments); }
export function option() { return el("option", ...arguments); }
export function header() { return el("header", ...arguments); }
export function footer() { return el("footer", ...arguments); }
export function section() { return el("section", ...arguments); }
export function article() { return el("article", ...arguments); }
export function aside() { return el("aside", ...arguments); }
export function nav() { return el("nav", ...arguments); }
export function main() { return el("main", ...arguments); }
export function figure() { return el("figure", ...arguments); }
export function figcaption() { return el("figcaption", ...arguments); }
export function video() { return el("video", ...arguments); }
export function svg() { return el("svg", ...arguments); }
export function iframe() { return el("iframe", ...arguments); }
export function blockquote() { return el("blockquote", ...arguments); }
export function cite() { return el("cite", ...arguments); }
export function time() { return el("time", ...arguments); }
export function mark() { return el("mark", ...arguments); }
export function progress() { return el("progress", ...arguments); }
export function meter() { return el("meter", ...arguments); }
export function details() { return el("details", ...arguments); }
export function summary() { return el("summary", ...arguments); }
export function dialog() { return el("dialog", ...arguments); }
export function template() { return el("template", ...arguments); }
export function script() { return el("script", ...arguments); }
export function meta() { return el("meta", ...arguments); }
export function title() { return el("title", ...arguments); }
export function area() { return el("area", ...arguments); }
export function audio() { return el("audio", ...arguments); }
export function canvas() { return el("canvas", ...arguments); }
export function col() { return el("col", ...arguments); }
export function colgroup() { return el("colgroup", ...arguments); }
export function hr() { return el("hr", ...arguments); }
export function keygen() { return el("keygen", ...arguments); }
export function param() { return el("param", ...arguments); }
export function source() { return el("source", ...arguments); }
export function track() { return el("track", ...arguments); }